# Generated by Django 6.0.1 on 2026-01-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('marketplace', '0002_auctionevent_bid_is_auto_bid_bid_is_winning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceGuideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(max_length=550, unique=True)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('set_name', models.CharField(blank=True, max_length=200)),
                ('card_number', models.CharField(blank=True, max_length=50)),
                ('variant', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('issue_number', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='price_guide/')),
                ('total_sales', models.IntegerField(default=0)),
                ('avg_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_sale_date', models.DateTimeField(blank=True, null=True)),
                ('price_trend', models.CharField(default='stable', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_guide_items', to='items.category')),
            ],
            options={
                'ordering': ['-total_sales', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_company', models.CharField(choices=[('raw', 'Raw/Ungraded'), ('psa', 'PSA'), ('bgs', 'BGS'), ('cgc', 'CGC'), ('sgc', 'SGC'), ('cbcs', 'CBCS')], max_length=10)),
                ('grade', models.DecimalField(decimal_places=1, max_digits=3)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('median_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('num_sales', models.IntegerField(default=0)),
                ('last_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_sale_date', models.DateTimeField(blank=True, null=True)),
                ('price_change_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price_guide_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_prices', to='pricing.priceguideitem')),
            ],
            options={
                'ordering': ['-grade'],
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateTimeField()),
                ('source', models.CharField(choices=[('heroesandmore', 'HeroesAndMore'), ('ebay', 'eBay'), ('heritage', 'Heritage Auctions'), ('goldin', 'Goldin'), ('pwcc', 'PWCC'), ('manual', 'Manual Entry')], max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('grading_company', models.CharField(blank=True, max_length=10)),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cert_number', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.listing')),
                ('price_guide_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pricing.priceguideitem')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.AddIndex(
            model_name='priceguideitem',
            index=models.Index(fields=['name', 'year'], name='pricing_pri_name_ff5ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='priceguideitem',
            index=models.Index(fields=['category', 'year'], name='pricing_pri_categor_71df0f_idx'),
        ),
        migrations.AddIndex(
            model_name='priceguideitem',
            index=models.Index(fields=['set_name', 'year'], name='pricing_pri_set_nam_34b39e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeprice',
            unique_together={('price_guide_item', 'grading_company', 'grade')},
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['price_guide_item', 'sale_date'], name='pricing_sal_price_g_7e26ee_idx'),
        ),
        migrations.AddIndex(
            model_name='salerecord',
            index=models.Index(fields=['sale_date'], name='pricing_sal_sale_da_f933f2_idx'),
        ),
    ]
