# Generated by Django 6.0.1 on 2026-02-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceguideitem',
            name='image_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='priceguideitem',
            name='image_source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='source',
            field=models.CharField(choices=[('heroesandmore', 'HeroesAndMore'), ('ebay', 'eBay'), ('heritage', 'Heritage Auctions'), ('gocollect', 'GoCollect'), ('goldin', 'Goldin'), ('pwcc', 'PWCC'), ('manual', 'Manual Entry')], max_length=20),
        ),
    ]
