# Generated by Django 6.0.1 on 2026-02-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_priceguideitem_image_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
