# Generated by Django 6.0.1 on 2026-02-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_salerecord_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='source_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
