# Generated by Django 6.0.1 on 2026-03-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
        ('marketplace', '0017_paypal_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatecommission',
            name='commission_type',
            field=models.CharField(choices=[('buyer', 'Buyer Referral'), ('seller', 'Seller Referral')], default='buyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='affiliatecommission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to='marketplace.order'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliatecommission',
            unique_together={('order', 'commission_type')},
        ),
    ]
