# Generated by Django 6.0.1 on 2026-01-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('event_type', models.CharField(choices=[('weekly', 'Weekly Auction'), ('themed', 'Themed Event'), ('elite', 'Elite Auction'), ('flash', 'Flash Sale')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('preview_start', models.DateTimeField()),
                ('bidding_start', models.DateTimeField()),
                ('bidding_end', models.DateTimeField()),
                ('cover_image', models.ImageField(blank=True, upload_to='auction_events/')),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preview', 'Preview'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_lots', models.IntegerField(default=0)),
                ('total_bids', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-bidding_start'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='is_auto_bid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='is_winning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='max_bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='triggered_extension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='auto_identified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='extended_bidding_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='listing',
            name='identification_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='lot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='minimum_offer_percent',
            field=models.IntegerField(default=70, help_text='Minimum offer as % of price'),
        ),
        migrations.AddField(
            model_name='listing',
            name='no_reserve',
            field=models.BooleanField(default=True),
        ),
    ]
