# Generated by Django 6.0.1 on 2026-01-29 15:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auctionevent_bid_is_auto_bid_bid_is_winning_and_more'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_guide_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='pricing.priceguideitem'),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.99'), max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='times_extended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='use_extended_bidding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='counter_message',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='countered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('countered', 'Countered'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='auctionevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_events_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='auction_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='marketplace.auctionevent'),
        ),
    ]
