# Generated by Django 6.0.1 on 2026-02-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_listing_image1_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of items available'),
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
