# Generated by Django 6.0.1 on 2026-02-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_listing_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionevent',
            name='cadence',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('special', 'Special/One-off')], max_length=20),
        ),
        migrations.AddField(
            model_name='auctionevent',
            name='is_platform_event',
            field=models.BooleanField(default=False, help_text='Platform-controlled auction event'),
        ),
    ]
