# Generated by Django 6.0.1 on 2026-02-14 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auctionevent_cadence_auctionevent_is_platform_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionevent',
            name='accepting_submissions',
            field=models.BooleanField(default=False, help_text='Allow trusted sellers to submit lots'),
        ),
        migrations.AddField(
            model_name='auctionevent',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuctionLotSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('auction_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='marketplace.auctionevent')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_submissions', to='marketplace.listing')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('auction_event', 'listing')},
            },
        ),
    ]
