# Generated by Django 6.0.1 on 2026-02-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auctionevent_accepting_submissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionevent',
            name='cover_image_position_x',
            field=models.IntegerField(default=50, help_text='Horizontal focal point (0-100%)'),
        ),
        migrations.AddField(
            model_name='auctionevent',
            name='cover_image_position_y',
            field=models.IntegerField(default=50, help_text='Vertical focal point (0-100%)'),
        ),
    ]
