# Generated by Django 6.0.1 on 2026-02-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_listing_collector_notes_order_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='listings/videos/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='listings/videos/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='listings/videos/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL', max_length=500),
        ),
    ]
