# Generated by Django 6.0.1 on 2026-02-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_add_video_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='customs_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='height_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='hs_tariff_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='length_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='shipping_mode',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('calculated', 'Calculated (EasyPost)'), ('free', 'Free Shipping')], default='flat', max_length=20),
        ),
    ]
