# Generated by Django 6.0.1 on 2026-02-25 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_listing_customs_description_listing_height_in_and_more'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='shipping_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='shipping.shippingprofile'),
        ),
        migrations.AddField(
            model_name='listing',
            name='weight_oz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='width_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='easypost_shipment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='label_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_carrier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_mode',
            field=models.CharField(default='flat', max_length=20),
        ),
    ]
