# Generated by Django 6.0.1 on 2026-03-04 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('marketplace', '0015_listing_shipping_profile_listing_weight_oz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestListingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('collector_notes', models.CharField(blank=True, max_length=300)),
                ('condition', models.CharField(choices=[('mint', 'Mint'), ('near_mint', 'Near Mint'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('grading_service', models.CharField(blank=True, choices=[('', 'None'), ('psa', 'PSA'), ('bgs', 'BGS'), ('cgc', 'CGC'), ('sgc', 'SGC')], max_length=10)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('cert_number', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('listing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('auction', 'Auction')], default='fixed', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allow_offers', models.BooleanField(default=False)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='guest_submissions/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='guest_submissions/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='guest_submissions/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='guest_submissions/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='guest_submissions/')),
                ('shipping_mode', models.CharField(choices=[('flat', 'Flat Rate'), ('calculated', 'Calculated (EasyPost)'), ('free', 'Free Shipping')], default='flat', max_length=20)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ships_from', models.CharField(blank=True, max_length=100)),
                ('source_category_key', models.CharField(help_text='Sell page category slug e.g. mtg, pokemon', max_length=50)),
                ('utm_source', models.CharField(blank=True, max_length=200)),
                ('utm_medium', models.CharField(blank=True, max_length=200)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
                ('converted_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_submission', to='marketplace.listing')),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
