# Generated by Django 6.0.1 on 2026-03-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_guest_listing_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Credit/Debit Card'), ('paypal', 'PayPal')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_capture_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_payout_batch_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
