# Generated by Django 6.0.1 on 2026-02-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_default_payment_method_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_new_bid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_offer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_order_shipped',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_outbid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='push_price_alert',
            field=models.BooleanField(default=True),
        ),
    ]
