# Generated by Django 6.0.1 on 2026-02-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_push_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_platform_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_trusted_seller',
            field=models.BooleanField(default=False),
        ),
    ]
