# Generated by Django 6.0.1 on 2026-02-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_is_platform_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_country',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
