# Generated by Django 6.0.1 on 2026-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_stripe_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='founding_member_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_founding_member',
            field=models.BooleanField(default=False),
        ),
    ]
