# Generated by Django 6.0.1 on 2026-02-24 20:56

from django.db import migrations
from django.utils import timezone


def backfill_founding_members(apps, schema_editor):
    """Set all existing users as founding members."""
    Profile = apps.get_model('accounts', 'Profile')
    now = timezone.now()
    Profile.objects.filter(is_founding_member=False).update(
        is_founding_member=True,
        founding_member_since=now,
    )


def reverse_backfill(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.update(is_founding_member=False, founding_member_since=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_founding_member_since_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_founding_members, reverse_backfill),
    ]
