# Generated by Django 6.0.1 on 2026-02-25 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_backfill_founding_members'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_ship_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipping.address'),
        ),
    ]
