# Generated by Django 6.0.1 on 2026-02-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_default_ship_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_bidding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_listings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_marketing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_offers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
