# Generated by Django 6.0.1 on 2026-03-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_email_bidding_profile_email_listings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='PayPal email for receiving payouts', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_payout_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], default='stripe', help_text='Preferred method for receiving sale payouts', max_length=20),
        ),
    ]
