# Generated by Django 5.2.12 on 2026-03-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_email_price_drops_post_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
