# Generated by Django 6.0.1 on 2026-01-29 15:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('user_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='collection',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='collection',
            name='value_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='cert_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='grading_company',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='price_guide_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_items', to='pricing.priceguideitem'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='value_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CollectionValueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('item_count', models.IntegerField()),
                ('value_by_category', models.JSONField(blank=True, default=dict)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_snapshots', to='user_collections.collection')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('collection', 'date')},
            },
        ),
    ]
