# Generated by Django 6.0.1 on 2026-01-29 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('marketplace', '0003_listing_price_guide_item_listing_starting_bid_and_more'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='grading_company',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='matches_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='min_grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='notify_frequency',
            field=models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='instant', max_length=20),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='notify_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='query',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price_guide_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='pricing.priceguideitem')),
                ('triggered_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='marketplace.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
