# Generated by Django 6.0.1 on 2026-02-16 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_savedsearch_filters_savedsearch_grading_company_and_more'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('price_drop', 'Price Drop'), ('new_listing', 'New Listing Match'), ('auction_ending', 'Auction Ending Soon'), ('outbid', 'Outbid'), ('order_update', 'Order Update'), ('message', 'New Message'), ('review', 'New Review'), ('follower', 'New Follower'), ('wishlist_match', 'Wishlist Match'), ('listing_expired', 'Listing Expired'), ('relist_reminder', 'Relist Reminder'), ('auction_event', 'Auction Event')], max_length=20),
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(max_length=64, unique=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.CharField(max_length=64, unique=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Interested categories (empty = all/general)', to='items.category')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
