# Generated by Django 5.2.10 on 2026-01-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellersubscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellersubscription',
            name='subscription_status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('suspended', 'Suspended')], default='inactive', max_length=30),
        ),
    ]
