# Generated by Django 6.0.1 on 2026-02-25 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0014_listing_customs_description_listing_height_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('profile_type', models.CharField(choices=[('standard_card', 'Standard Card (PWE)'), ('graded_slab', 'Graded Slab'), ('multiple_cards', 'Multiple Cards / Lot'), ('figure_toy', 'Figure / Toy'), ('custom', 'Custom')], max_length=20)),
                ('weight_oz', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length_in', models.DecimalField(decimal_places=2, max_digits=6)),
                ('width_in', models.DecimalField(decimal_places=2, max_digits=6)),
                ('height_in', models.DecimalField(decimal_places=2, max_digits=6)),
                ('predefined_package', models.CharField(blank=True, help_text='EasyPost predefined package name', max_length=50)),
                ('customs_description', models.CharField(blank=True, max_length=200)),
                ('hs_tariff_number', models.CharField(blank=True, help_text='Harmonized System tariff code', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('street1', models.CharField(max_length=200)),
                ('street2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='US', max_length=2)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('easypost_id', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'ordering': ['-is_default', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easypost_shipment_id', models.CharField(max_length=100)),
                ('easypost_label_id', models.CharField(blank=True, max_length=100)),
                ('carrier', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('label_url', models.URLField(blank=True, max_length=500)),
                ('label_format', models.CharField(default='PDF', max_length=10)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_labels', to='marketplace.order')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easypost_shipment_id', models.CharField(max_length=100)),
                ('easypost_rate_id', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('est_delivery_days', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='marketplace.listing')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_quotes', to='shipping.address')),
            ],
            options={
                'ordering': ['rate'],
            },
        ),
    ]
