# Generated by Django 6.0.1 on 2026-02-25 23:21

from django.db import migrations


def seed_profiles(apps, schema_editor):
    ShippingProfile = apps.get_model('shipping', 'ShippingProfile')
    profiles = [
        {
            'name': 'Standard Card (PWE)',
            'slug': 'standard-card',
            'profile_type': 'standard_card',
            'weight_oz': 2,
            'length_in': 9.5,
            'width_in': 6.5,
            'height_in': 0.25,
            'customs_description': 'Trading card',
            'hs_tariff_number': '9504.40',
            'sort_order': 1,
        },
        {
            'name': 'Graded Slab',
            'slug': 'graded-slab',
            'profile_type': 'graded_slab',
            'weight_oz': 8,
            'length_in': 10,
            'width_in': 7,
            'height_in': 2,
            'customs_description': 'Graded collectible card in protective case',
            'hs_tariff_number': '9504.40',
            'sort_order': 2,
        },
        {
            'name': 'Multiple Cards / Lot',
            'slug': 'multiple-cards',
            'profile_type': 'multiple_cards',
            'weight_oz': 16,
            'length_in': 11,
            'width_in': 8.5,
            'height_in': 3,
            'customs_description': 'Trading cards lot',
            'hs_tariff_number': '9504.40',
            'sort_order': 3,
        },
        {
            'name': 'Figure / Toy',
            'slug': 'figure-toy',
            'profile_type': 'figure_toy',
            'weight_oz': 32,
            'length_in': 14,
            'width_in': 10,
            'height_in': 6,
            'customs_description': 'Collectible figure',
            'hs_tariff_number': '9503.00',
            'sort_order': 4,
        },
        {
            'name': 'Custom',
            'slug': 'custom',
            'profile_type': 'custom',
            'weight_oz': 8,
            'length_in': 10,
            'width_in': 7,
            'height_in': 2,
            'customs_description': 'Collectible item',
            'sort_order': 5,
        },
    ]
    for profile_data in profiles:
        ShippingProfile.objects.get_or_create(
            slug=profile_data['slug'],
            defaults=profile_data,
        )


def reverse_seed(apps, schema_editor):
    ShippingProfile = apps.get_model('shipping', 'ShippingProfile')
    ShippingProfile.objects.filter(slug__in=[
        'standard-card', 'graded-slab', 'multiple-cards', 'figure-toy', 'custom'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_profiles, reverse_seed),
    ]
